
server.port=8080
spring.application.name=main-server

stats-server.url=http://stats-server:9090


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop
spring.jpa.properties.hibernate.connection.initSQL=CREATE DATABASE IF NOT EXISTS main
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=true

logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=INFO
logging.level.ru.practicum.stats.client=DEBUG