
server.port=8080
spring.application.name=main-server

stats-server.url=http://localhost:9090

stats-server.connect-timeout=5
stats-server.read-timeout=10

spring.datasource.url=jdbc:postgresql://localhost:5432/main
spring.datasource.username=main_user
spring.datasource.password=main_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.ru.practicum=DEBUG
logging.level.org.springframework.web=INFO
logging.level.ru.practicum.stats.client=DEBUG